### ISSUE TITLE
API works for an hour then fails

### ISSUE THREAD

**Issue by israndy** [scottbonline/sense#56] opened 2023-01-03 22:49 UTC
To troubleshoot I copied the code from the read me here and wrote this script:

```
from sense_energy import Senseable
import datetime
from time import sleep
sense = Senseable()
sense.authenticate('israndy@yahoo.com', 'XXX')

def printmsg(msg) :                                        # Timestamped message
    print( " ", datetime.datetime.now().strftime( "%a %I:%M %p" ), msg )
    
while True:
    try:
        sense.update_realtime()
        sense.update_trend_data()
    except :
        printmsg("\033[31mSense Timeout\033[m")
        sleep(120)
        continue
    else :
        print ("Active:", sense.active_power, "W")
        print ("Active Solar:", sense.active_solar_power, "W")
        print ("Daily:", sense.daily_usage, "KWh")
        print ("Daily Solar:", sense.daily_production, "KWh")
        print ("Active Devices:",", ".join(sense.active_devices))
        printmsg('Wait three minutes...')
        sleep(180)
```

After one hour I get Sense Timeouts until I quit and relaunch the app, identical to how my original code is behaving.

I recently updated my Python but that shouldn't break the API

**Comment by kbickar** [comment] 2023-01-04 20:07
Duplicate of #55

**Closed as not planned by kbickar** 2023-01-04 20:07 UTC
